#!perl

use strict;
use warnings;

use Getopt::Long;
use App::Fey qw(fey);

my $options = {
    context => undef,
    fork => 0,
    group => 0,
    interactive => 0,
    single => 0
};

GetOptions(
    'c|context:s' => \$options->{context},
    'f|fork' => \$options->{fork},
    'g|group' => \$options->{group},
    'i|interactive' => \$options->{interactive},
    's|single' => \$options->{single}
);

fey $options, @ARGV;
